### ISSUE TITLE
highlight color looks wrong with apprentice color scheme

### ISSUE THREAD

**Issue by lavie** [axlebedev/footprints#1]
On a Mac, I have the `apprentice` colorscheme (on a dark background) and the out-of-the-box default of `foorprints` has the following orange highlight that kind of doesn't work, as you can see:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/233414/128590458-556e2f0a-257b-4162-9007-7d6ace2545dd.png">

**Comment by axlebedev** [comment]
Looks like you use terminal colors.
Please check `&termguicolors`
If it's false - you should use terminal settings: `g:footprintsTermColor` or `footprints#SetTermColor(termColorCode: number)`
