### ISSUE TITLE
Undefined Variable "IsBufLocal" Causing Error on Start up

### ISSUE THREAD

**Issue by acherrera** [axlebedev/footprints#2]
Looking at the runtime log on start up, the full error is:

```
line 0: sourcing "/home/tony/.vim/plugged/footprints/autoload/footprints.vim"
Error detected while processing /home/tony/.vim/plugged/footprints/autoload/footprints.vim:
line   72:
E475: Invalid argument: isBufLocal = 0) abort
line   73:
E121: Undefined variable: a:isBufLocal
E15: Invalid expression: (a:isBufLocal)
```

I was actually writing this issue up when I solved it myself. Going to create the issue with a solution to save other people asking later.  I was running Neovim V0.4.3, so I went to check the most recent version which happened to be NeoVim V0.5.0. After pulling down the new NeoVim  the error went away. 

For anyone who gets this error in the future - try upgrading NeoVim.

**Comment by Chilinot** [comment]
Thanks, had the same issue and only had to update my neovim version :)

Perhaps a requirement on NeoVim 0.5+ should be in a requirement list of this repo/plugin.

**Comment by axlebedev** [comment]
Thank you!
Updated readme and added condition to load guard
