### ISSUE TITLE
increasing foot dept will give error when opening old file where depth was lower

### ISSUE THREAD

**Issue by JoseConseco** [axlebedev/footprints#4]
I bumped foot depth from 10 to 15. Now when I open old file that was edited using 10 dept I get this errors:
![image](https://user-images.githubusercontent.com/13521338/132058641-6bfe6469-586d-4a14-b546-293082dc1a11.png)

**Comment by axlebedev** [comment]
Thank you!
Worked around this issue.
--
Snoozed annoying error message. Show more useful once.
--
Added [footprints#SetHistoryDepth](https://github.com/axlebedev/footprints#footprintssethistorydepthdepth-number) to make it possible change depth in runtime.
