### ISSUE TITLE
Add option to mark the postion to vim mark

### ISSUE THREAD

**Issue by dvtalk** [axlebedev/footprints#8]
Hi,
Could you consider to store a postion of last edited line to a mark in vim.
I think it would be easier if we could jump to the editted line as well.

Thanks a lot for the plugin anyway.

**Comment by axlebedev** [comment]
Hello! Thank you!
Would you tell, what's wrong with default keymaps `g;` and `g,` ?
They do exactly you want

**Comment by dvtalk** [comment]
Do not aware that those keymaps exists.
Thanks a lot =D
